# Generated by Django 3.1.2 on 2020-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEM13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmi', models.CharField(max_length=10)),
                ('reading_time', models.DateTimeField(verbose_name='date published')),
                ('serial_number', models.CharField(max_length=12)),
                ('reading_value', models.CharField(max_length=15)),
                ('filename', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
